services:
    monolith:
        image: 'monolith_02_01:latest'
        restart: 'always'
        container_name: 'monolith'
        ports:
            - '3000:3000'
        volumes:
            - ./config.dev.json:/app/config.json
        depends_on:
            - postgres

    postgres:
        image: 'postgres'
        restart: 'always'
        container_name: 'postgres'
        environment:
            POSTGRES_PASSWORD: pass
            POSTGRES_USER: user
            POSTGRES_DB: test
        # ports:
        #     - '5432:5432'
        volumes:
            - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
